# Generated by Django 4.1.3 on 2022-12-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WilayahDBAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_wilayah", models.CharField(blank=True, max_length=200, null=True)),
                ("prov", models.CharField(blank=True, max_length=200, null=True)),
                ("kab", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
